In [1]:
import pandas as pd
import re
import numpy as np
from pandas import Series, DataFrame
import locale
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')

'en_US.UTF-8'

In [2]:
#df = pd.read_csv(r"C:\Users\user\OneDrive\桌面\data12.csv",encoding="cp950")
df = pd.read_excel(r"C:\Users\user\OneDrive\桌面\data12clean.xlsx")
dfnmv = df

dfnm = dfnmv.dropna()

#dfnmv

In [3]:
col = dfnm.shape[1]
row = dfnm.shape[0]
# df["流動資產"]
# df["流動負債"]
#df.insert(i+2,lv1[i],aa)
dfnm.insert(col,"wc",0)

In [4]:
ind = dfnm.columns.tolist()
cacol = ind.index("流動資產")
clcol = ind.index("流動負債")
wccol = ind.index("wc")

for i in range(0,row):
    #print(i)
    a = dfnm.iloc[i,cacol]
    b = dfnm.iloc[i,clcol]
    a = int(locale.atof(a))
    b = int(locale.atof(b))
    dfnm.iloc[i,wccol] = a-b
#dfnm

C:\Users\user\Anaconda3\anaconda3-1\lib\site-packages\pandas\core\indexing.py:1719: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [5]:
dfnm[['流動資產','資產總額','流動負債']] = dfnm[['流動資產','資產總額','流動負債']].astype(str)
dfnm[['負債總額','保留盈餘','營業收入淨額']] = dfnm[['負債總額','保留盈餘','營業收入淨額']] .astype(str)
dfnm[['稅前息前淨利','稅前淨利','所得稅費用']] = dfnm[['稅前息前淨利','稅前淨利','所得稅費用']].astype(str)

C:\Users\user\Anaconda3\anaconda3-1\lib\site-packages\pandas\core\frame.py:3188: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [6]:
dfnm.insert(col+1,"x1",0)
dfnm.insert(col+2,"x2",0)
dfnm.insert(col+3,"x3",0)
dfnm.insert(col+4,"x4",0)
dfnm.insert(col+5,"x5",0)
dfnm.insert(col+6,"z",0)

In [7]:
ind = dfnm.columns.tolist()
ind
wccol = ind.index("wc")
tacol = ind.index("資產總額")
recol = ind.index("保留盈餘")
ebitcol = ind.index("稅前息前淨利")
mvcol = ind.index("wc")
scol = ind.index("營業收入淨額")
tlcol = ind.index("負債總額")
mvcol = ind.index("市值(百萬元)")
x1col = ind.index("x1")
x2col = ind.index("x2")
x3col = ind.index("x3")
x4col = ind.index("x4")
x5col = ind.index("x5")
zcol = ind.index("z")
ind

['Unnamed: 0',
 '年月',
 '公司',
 '證期會代碼',
 '流動資產',
 '資產總額',
 '流動負債',
 '負債總額',
 '保留盈餘',
 '營業收入淨額',
 '稅前息前淨利',
 '稅前淨利',
 '所得稅費用',
 '來自營運之現金流量',
 '市值(百萬元)',
 'wc',
 'x1',
 'x2',
 'x3',
 'x4',
 'x5',
 'z']

In [8]:
dfnm
for i in range(0,row):
    a = dfnm.iloc[i,wccol]
    b = dfnm.iloc[i,tacol]
    b = int(locale.atof(b))
    c = (a/b)
    dfnm.iloc[i,x1col] = c

for i in range(0,row):
    #print(i)
    a = dfnm.iloc[i,recol]
    b = dfnm.iloc[i,tacol]
    a = int(locale.atof(a))
    b = int(locale.atof(b))
    c = (a/b)
    dfnm.iloc[i,x2col] = c

for i in range(0,row):
    a = dfnm.iloc[i,ebitcol]
    b = dfnm.iloc[i,tacol]
    a = int(locale.atof(a))
    b = int(locale.atof(b))
    c = (a/b)
    dfnm.iloc[i,x3col] = c
    
for i in range(0,row):
    a = dfnm.iloc[i,mvcol]
    b = dfnm.iloc[i,tlcol]
    a = int(locale.atof(a))
    b = int(locale.atof(b))
    c = (a*1000/b)
    dfnm.iloc[i,x4col] = c
    
for i in range(0,row):
    #print(i)
    a = dfnm.iloc[i,scol]
    b = dfnm.iloc[i,tacol]
    a = int(locale.atof(a))
    b = int(locale.atof(b))
    c = (a/b)
    dfnm.iloc[i,x5col] = c
#dfnm

In [9]:
#dfnm.iloc[8003,:]

In [10]:
beta1 = 1.2
beta2 = 1.4
beta3 = 3.3
beta4 = 0.6
beta5 = 0.999


for i in range(0,row):
    x1 = dfnm.iloc[i,x1col]
    x2 = dfnm.iloc[i,x2col]
    x3 = dfnm.iloc[i,x3col]
    x4 = dfnm.iloc[i,x4col]
    x5 = dfnm.iloc[i,x5col]
    c = x1*beta1 + x2*beta2 + x3*beta3 + x4*beta4 + x5*beta5
    dfnm.iloc[i,zcol] = c
dfnm

,Unnamed: 0,年月,公司,證期會代碼,流動資產,資產總額,流動負債,負債總額,保留盈餘,營業收入淨額,...,所得稅費用,來自營運之現金流量,市值(百萬元),wc,x1,x2,x3,x4,x5,z
0,0,2016/12/30,1101 台泥,1101,"77,884,012","266,988,696","55,104,919","119,592,025","47,337,524","89,564,306",...,"2,673,260","18,750,155","129,780",22779093,0.085319,0.177302,0.050310,1.085189,0.335461,1.502866
1,1,2016/12/30,1102 亞泥,1102,"42,148,568","238,470,785","40,857,530","97,807,564","91,599,413","60,946,190",...,"1,793,292","12,817,431","88,574",1291038,0.005414,0.384112,0.034029,0.905595,0.255571,1.455219
2,2,2016/12/30,1103 嘉泥,1103,"9,443,483","26,128,917","1,981,486","10,315,659","8,335,423","3,140,190",...,"69,355","414,899","6,764",7461997,0.285584,0.319011,0.010364,0.655702,0.120181,1.336998
3,3,2016/12/30,1104 環泥,1104,"3,644,849","20,347,150","2,569,341","3,951,027","9,650,044","4,622,199",...,"94,984","741,025","15,642",1075508,0.052858,0.474270,0.088231,3.958971,0.227167,3.620893
5,5,2016/12/30,1108 幸福,1108,"5,360,762","7,752,644","2,604,897","2,950,808","696,907","4,251,061",...,"77,128","246,301","3,691",2755865,0.355474,0.089893,0.055796,1.250844,0.548337,2.034842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38175,38466,1989/12/28,8722 尚德,8722,"668,285","1,323,280","606,257","666,881","69,531","1,211,595",...,"6,892","63,446","5,654",62028,0.046874,0.052544,0.060690,8.478274,0.915600,6.331738
38187,38478,1989/12/28,9801 力霸,9801,"4,706,413","11,957,001","3,005,346","3,485,207","598,612","6,158,129",...,"96,000","198,632","37,917",1701067,0.142265,0.050064,0.067030,10.879411,0.515023,7.504160
38188,38479,1989/12/28,9902 台火,9902,"86,056","1,136,777","39,379","131,869","558,228","19,424",...,"10,263","96,094","24,424",46677,0.041061,0.491062,0.308981,185.214114,0.017087,112.901937
38189,38480,1989/12/28,9903 光男,992026,"4,175,444","6,911,314","1,928,797","2,108,875","649,954","4,651,212",...,"65,000","-116,430","17,280",2246647,0.325068,0.094042,0.096229,8.193942,0.672985,6.427975
38217,38508,1989/12/28,L2301 光寶,L2301,"1,292,414","2,580,843","1,058,518","1,459,544","178,001","2,361,585",...,"-2,152","41,038","12,046",233896,0.090628,0.068970,0.073803,8.253263,0.915044,6.314948

In [11]:
dfnm.to_csv("1012z.csv")